files: application-deadline-reminder/
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      args:
        - --target-version=py310
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  -   id: detect-secrets
      args: ['--disable-plugin', 'HexHighEntropyString',
        '--disable-plugin', 'Base64HighEntropyString']
      exclude: tests/keys/rsa256
