Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Resources:
  ApplicationDeadlineReminderRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: !Sub ApplicationDeadlineReminderPolicy${Env}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'
                Effect: Allow
              - Action:
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeInstances'
                  - 'ec2:AttachNetworkInterface'
                Resource:
                  - '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com

  ApplicationDeadlineReminderLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: lambdas/application-deadline-reminder/
      Handler: sentry_sdk.integrations.init_serverless_sdk.sentry_lambda_handler
      Timeout: 900
      MemorySize: 512
      Role: !GetAtt ApplicationDeadlineReminderRole.Arn
      Runtime: python3.11
      Environment:
        Variables:
          ACCOUNTS_ENDPOINT: /accounts
          ACCOUNT_STORE_API_HOST: !Sub http://fsd-pre-award.${Env}.pre-award.local:8080/account
          APPLICATIONS_ENDPOINT: /applications
          APPLICATION_ENDPOINT: /applications/{application_id}
          APPLICATION_REMINDER_STATUS: /funds/{round_id}/application_reminder_status?status=true
          APPLICATION_STORE_API_HOST: !Sub http://fsd-pre-award.${Env}.pre-award.local:8080/application
          FUND_ENDPOINT: /funds/{fund_id}
          FUNDS_ENDPOINT: /funds
          FUND_ROUNDS_ENDPOINT: /funds/{fund_id}/rounds
          FUND_EVENTS_ENDPOINT: /funds/{fund_id}/rounds/{round_id}/events
          FUND_EVENT_ENDPOINT: /funds/{fund_id}/rounds/{round_id}/event/{event_id}
          FUND_STORE_API_HOST: !Sub http://fsd-pre-award.${Env}.pre-award.local:8080/fund
          NOTIFICATION_SERVICE_API_HOST: !Sub http://fsd-notification.${Env}.pre-award.local:8080
          NOTIFY_TEMPLATE_APPLICATION_DEADLINE_REMINDER: APPLICATION_DEADLINE_REMINDER
          NOTIFY_TEMPLATE_INCOMPLETE_APPLICATION: INCOMPLETE_APPLICATION_RECORDS
          AWS_MSG_BUCKET_NAME: !ImportValue
            'Fn::Sub': "${App}-${Env}-MessageBucket"
          AWS_SQS_NOTIF_APP_PRIMARY_QUEUE_URL: !ImportValue
            'Fn::Sub': "${App}-${Env}-NotificationQueueURL"
          AWS_SQS_NOTIF_APP_SECONDARY_QUEUE_URL: !ImportValue
            'Fn::Sub': "${App}-${Env}-NotificationDeadLetterQueueURL"
          SENTRY_DSN: https://80c7f65b54f0eff535777a66b375adf0@o1432034.ingest.us.sentry.io/4508324370317312
          SENTRY_ENVIRONMENT: !Sub ${Env}
          SENTRY_INITIAL_HANDLER: lambda_function.lambda_handler
          SENTRY_TRACES_SAMPLE_RATE: 1
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: "fsdfundstoreclusterSecurityGroup"
          - Fn::ImportValue: !Sub ${App}-${Env}-InternalLoadBalancerSecurityGroup
          - Fn::ImportValue: !Sub ${App}-${Env}-EnvironmentSecurityGroup
        SubnetIds:
          !Split
            - ','
            - Fn::ImportValue: !Sub ${App}-${Env}-PrivateSubnets
      Layers:
        - arn:aws:lambda:eu-west-2:378673660975:layer:python-modules:1
        - arn:aws:lambda:eu-west-2:943013980633:layer:SentryPythonServerlessSDK:138
        

  ApplicationDeadlineReminderLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      Description: Creation a version of the Application Deadline Reminder Lambda
      FunctionName: !Ref ApplicationDeadlineReminderLambdaFunction

  ApplicationDeadlineReminderScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Application Deadline Reminder Scheduled Rule"
      ScheduleExpression: "cron(30 09 * * ? *)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt ApplicationDeadlineReminderLambdaFunction.Arn
          Id: "TargetApplicationDeadlineReminderFunctionV1"

  ApplicationDeadlineReminderPermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApplicationDeadlineReminderLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ApplicationDeadlineReminderScheduledRule.Arn

Outputs:
  ApplicationDeadlineReminderLambdaArn:
    Description: The ARN of the Application Deadline Reminder Lambda
    Value: !GetAtt ApplicationDeadlineReminderLambdaFunction.Arn
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ApplicationDeadlineReminderLambdaArn']]
  ApplicationDeadlineReminderLambdaVersion:
    Description: The version of the Application Deadline Reminder Lambda
    Value: !GetAtt ApplicationDeadlineReminderLambdaVersion.Version
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ApplicationDeadlineReminderLambdaVersion']]
