Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  FifoQueueName:
    Type: String
    Description: Fifo Queue Name
    Default: assessment-import-queue

Resources:
  AssessmentImportQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${FifoQueueName}-${Env}.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AssessmentImportDeadLetterQueue.Arn
        maxReceiveCount: 3
  AssessmentImportDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !Sub ${FifoQueueName}-${Env}-deadletter.fifo

  AssessmentImportQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AssessmentImportQueue
      PolicyDocument:
        Statement:
          -
            Action:
              - "SQS:SendMessage"
              - "SQS:ReceiveMessage"
              - "SQS:DeleteMessage"
            Effect: "Allow"
            Resource: !GetAtt AssessmentImportQueue.Arn
            Principal:
              AWS:
                - "*"

Outputs:
  AssessmentImportQueueURL:
    Description: Queue URL for Fifo queue
    Value: !Ref AssessmentImportQueue
    Export:
      Name: !Sub ${App}-${Env}-AssessmentImportQueueURL
  AssessmentImportQueueArn:
    Description: Queue Arn for FIFO queue
    Value: !GetAtt AssessmentImportQueue.Arn
    Export:
      Name: !Sub ${App}-${Env}-AssessmentImportQueueArn
  AssessmentImportDeadLetterQueueURL:
    Description: "URL of dead-letter queue"
    Value: !Ref AssessmentImportDeadLetterQueue
    Export:
      Name: !Sub ${App}-${Env}-AssessmentImportDeadLetterQueueURL
  AssessmentImportDeadLetterQueueARN:
    Description: "ARN of dead-letter queue"
    Value: !GetAtt AssessmentImportDeadLetterQueue.Arn
    Export:
      Name: !Sub ${App}-${Env}-AssessmentImportDeadLetterQueueARN
