Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: Your workload's name.
    Default: notification-queue

Resources:
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Name}-${Env}.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NotificationDeadLetterQueue.Arn
        maxReceiveCount: 3
  NotificationDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: !Sub ${Name}-${Env}-deadletter.fifo

  NotificationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref NotificationQueue
      PolicyDocument:
        Statement:
          -
            Action:
              - "SQS:SendMessage"
              - "SQS:ReceiveMessage"
              - "SQS:DeleteMessage"
            Effect: "Allow"
            Resource: !GetAtt NotificationQueue.Arn
            Principal:
              AWS:
                - "*"

Outputs:
  NotificationQueueURL:
    Description: Queue URL for Fifo queue
    Value: !Ref NotificationQueue
    Export:
      Name: !Sub ${App}-${Env}-NotificationQueueURL
  NotificationQueueArn:
    Description: Queue Arn for FIFO queue
    Value: !GetAtt NotificationQueue.Arn
    Export:
      Name: !Sub ${App}-${Env}-NotificationQueueArn
  NotificationDeadLetterQueueURL:
    Description: "URL of dead-letter queue"
    Value: !Ref NotificationDeadLetterQueue
    Export:
      Name: !Sub ${App}-${Env}-NotificationDeadLetterQueueURL
  NotificationDeadLetterQueueARN:
    Description: "ARN of dead-letter queue"
    Value: !GetAtt NotificationDeadLetterQueue.Arn
    Export:
      Name: !Sub ${App}-${Env}-NotificationDeadLetterQueueARN
