on:
    workflow_call:
        inputs:
            environment:
                type: string
                required: false
        outputs:
            jobs_to_run:
                description: List of jobs to run
                value: ${{jobs.determine-jobs-to-run.outputs.jobs_to_run}}

jobs:
    determine-jobs-to-run:
        runs-on: ubuntu-latest
        outputs: 
            jobs_to_run: ${{ steps.determine-jobs.outputs.job_list }}
        steps:
            - id: determine-jobs
              run: |
                    export jobs='["test", "uat"]'
                    echo "job_list=$(jq -cn --argjson keys "$jobs" '$keys')" >> $GITHUB_OUTPUT
                    cat $GITHUB_OUTPUT