on:
    workflow_call:
        inputs:
            environment:
                type: string
                required: false
        outputs:
            jobs_to_run:
                description: List of jobs to run
                value: ${{jobs.determine-jobs-to-run.outputs.jobs_to_run}}

jobs:
    determine-jobs-to-run:
        name: Determine jobs to run
        runs-on: ubuntu-latest
        outputs: 
            jobs_to_run: ${{ steps.determine-jobs.outputs.job_list }}
        steps:
            - id: determine-jobs
              env:
                ENVIRONMENT: ${{ inputs.environment }}
              run: |
                if [ "$ENVIRONMENT" != '' ]; then
                    export jobs=$(jq -cn --arg env "$ENVIRONMENT" '[$env]')
                elif [ "$GITHUB_REF" == 'refs/heads/main' ]; then
                    export jobs='["test", "uat", "prod"]'
                else
                    export jobs='[]'
                fi
                echo "job_list=$(jq -cn --argjson keys "$jobs" '$keys')" >> $GITHUB_OUTPUT
                cat $GITHUB_OUTPUT