name: Just Run Tests
on:
  workflow_dispatch:
    inputs:
      dev:
        required: false
        default: false
        type: boolean
      test:
        required: false
        default: false
        type: boolean
      uat:
        required: false
        default: false
        type: boolean
      run_performance_tests:
        required: false
        default: false
        type: boolean
        description: Run performance tests
      run_e2e_tests_application:
        required: false
        default: true
        type: boolean
        description: Run e2e tests (application)
      run_e2e_tests_assessment:
        required: false
        default: true
        type: boolean
        description: Run e2e tests (assessment)
      run_e2e_tests_python:
        required: false
        default: true
        type: boolean
        description: Run e2e tests (python)

jobs:
  run_shared_tests_dev:
    name: Run E2E tests (dev)
    if: ${{ always() && inputs.dev == true }}
    uses: ./.github/workflows/run-shared-tests.yml
    with:
      run_performance_tests: ${{inputs.run_performance_tests}}
      run_e2e_tests_application: ${{inputs.run_e2e_tests_application}}
      run_e2e_tests_assessment: ${{inputs.run_e2e_tests_assessment}}
      run_e2e_tests_python: ${{inputs.run_e2e_tests_python}}
      env_name: dev
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
      FS_BASIC_AUTH_USERNAME: ${{ secrets.FS_BASIC_AUTH_USERNAME }}
      FS_BASIC_AUTH_PASSWORD: ${{ secrets.FS_BASIC_AUTH_PASSWORD }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

  run_shared_tests_test:
    name: Run E2E tests (test)
    if: ${{ always() && inputs.test == true }}
    uses: ./.github/workflows/run-shared-tests.yml
    with:
      run_performance_tests: ${{inputs.run_performance_tests}}
      run_e2e_tests_application: ${{inputs.run_e2e_tests_application}}
      run_e2e_tests_assessment: ${{inputs.run_e2e_tests_assessment}}
      run_e2e_tests_python: ${{inputs.run_e2e_tests_python}}
      env_name: test
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
      FS_BASIC_AUTH_USERNAME: ${{ secrets.FS_BASIC_AUTH_USERNAME }}
      FS_BASIC_AUTH_PASSWORD: ${{ secrets.FS_BASIC_AUTH_PASSWORD }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

  run_shared_tests_uat:
    name: Run E2E tests (uat)
    if: ${{ always() && inputs.uat == true }}
    uses: ./.github/workflows/run-shared-tests.yml
    with:
      run_performance_tests: ${{inputs.run_performance_tests}}
      run_e2e_tests_application: ${{inputs.run_e2e_tests_application}}
      run_e2e_tests_assessment: ${{inputs.run_e2e_tests_assessment}}
      run_e2e_tests_python: false  # these tests don't work in UAT env
      env_name: uat
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
      FS_BASIC_AUTH_USERNAME: ${{ secrets.FS_BASIC_AUTH_USERNAME }}
      FS_BASIC_AUTH_PASSWORD: ${{ secrets.FS_BASIC_AUTH_PASSWORD }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
