on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      env_name:
        required: true
        type: string
      github_username:
        required: true
        type: string
      workflow_url:
        required: true
        type: string
      compare_url:
        required: false
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_NOTIFICATION_CHANNEL_ID:
        required: true

jobs:
  notify_slack:
    name: Slack failure notification
    runs-on: ubuntu-latest
    steps:
      - name: Check if deployment was manually rejected
        id: check-for-rejection
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # TODO: Remove this check if/when we move to continuous delivery with zero manual approvals.

          (gh run view --repo ${{ github.repository }} ${{ github.run_id }} | grep "The deployment was rejected or didn't satisfy other protection rules.") && rejected=true || rejected=false

          echo "manually-rejected=${rejected}" >> "$GITHUB_OUTPUT"
      - name: Send message to Slack (push)
        if: ${{ github.event_name == 'push' && steps.check-for-rejection.outputs.manually-rejected == 'false' }}
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_NOTIFICATION_CHANNEL_ID }}
            text: Deployment failed
            blocks:
            - type: section
              text:
                type: mrkdwn
                text: ":x: A deployment has failed - please investigate :x:"
            - type: section
              fields:
              - type: mrkdwn
                text: |-
                  *App:*
                  ${{ inputs.app_name }}
              - type: mrkdwn
                text: |-
                  *Environment:*
                  ${{ inputs.env_name }}
              - type: mrkdwn
                text: |-
                  *Commit author:*
                  ${{ inputs.github_username }}
              - type: mrkdwn
                text: |-
                  *Triggered by:*
                  Merged pull request
            - type: actions
              elements:
                - type: button
                  text:
                    type: plain_text
                    emoji: true
                    text: ":github: Open workflow run"
                  url: ${{ inputs.workflow_url }}
                - type: button
                  text:
                    type: plain_text
                    emoji: true
                    text: ":merged: View code changes"
                  url: ${{ inputs.compare_url }}
      - name: Send message to Slack (workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' && steps.check-for-rejection.outputs.manually-rejected == 'false'  }}
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_NOTIFICATION_CHANNEL_ID }}
            text: Deployment failed
            blocks:
            - type: section
              text:
                type: mrkdwn
                text: ":x: A deployment has failed - please investigate :x:"
            - type: section
              fields:
              - type: mrkdwn
                text: |-
                  *App:*
                  ${{ inputs.app_name }}
              - type: mrkdwn
                text: |-
                  *Environment:*
                  ${{ inputs.env_name }}
              - type: mrkdwn
                text: |-
                  *Commit author:*
                  ${{ inputs.github_username }}
              - type: mrkdwn
                text: |-
                  *Triggered by:*
                  Manual workflow run
            - type: actions
              elements:
                - type: button
                  text:
                    type: plain_text
                    emoji: true
                    text: ":github: Open workflow run"
                  url: ${{ inputs.workflow_url }}
