name: Optional jobs test
on:
  workflow_dispatch:
  push:
    paths:
       - ".github/workflows/opt_jobs.yml"

jobs:
  job1-always:
    runs-on: ubuntu-latest
    steps:
    - name: always_runs
      run: echo running always_runs in job1-always

  job2a:
    needs: job1-always
    runs-on: ubuntu-latest
    if: false
    steps:
    - name: optional-run
      run: echo running optional-run in job2a

  job2b:
    needs: job1-always
    runs-on: ubuntu-latest
    if: true
    steps:
    - name: optional-run
      run: echo running optional-run in job2b

  job3:
    needs: [job2a, job2b]
    if: ${{ always() && (needs.job2a.result=='success' || needs.job2b.result=='success') }}
    runs-on: ubuntu-latest
    steps:
    - name: always_runs
      run: echo running always_runs in job3

  job4:
    needs: [job3]
    if: ${{ always() && (needs.job3.result=='success') }}
    runs-on: ubuntu-latest
    steps:
    - name: always_runs
      run: echo running always_runs in job4