name: Use Paketo to package and build python application

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      assets_required:
        type: boolean
        default: false
      version_to_build:
        type: string
        required: true
      application:
        type: string
        required: true
      owner:
        type: string
        required: true
    outputs:
      image_location:
        description: "A URI pointing to the paketo-built image"
        value: ${{ jobs.paketo_build.outputs.image_location }}

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ inputs.application }}

jobs:
  paketo_build:
    runs-on: ubuntu-latest
    name: Packaging and building the application
    outputs:
      image_location: ${{ steps.build_and_publish.outputs.image_location }}
    steps:
      - uses: buildpacks/github-actions/setup-pack@v5.0.0
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: ${{inputs.assets_required == true}}
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.x

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: install dependencies
        if: ${{inputs.assets_required == true}}
        run: uv sync

      - name: build static assets (if frontend)
        if: ${{inputs.assets_required == true}}
        run: uv run python build.py

      - name: Build and publish app image
        id: build_and_publish
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ inputs.owner }}/${{ env.DOCKER_IMAGE }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ inputs.version_to_build }}
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          
          uv export --format requirements-txt --no-hashes > requirements.txt

          IMAGE_LOCATION="$IMAGE_ID:$VERSION"

          pack build $IMAGE_LOCATION --builder paketobuildpacks/builder-jammy-full --cache-image ${{ env.REGISTRY }}/${{ inputs.owner }}/${{ env.DOCKER_IMAGE }}/buildpack-packeto-cache-image --publish

          echo "image_location=$IMAGE_LOCATION" >> $GITHUB_OUTPUT
