on:
  workflow_call:
    inputs:
      run_e2e_tests:
        required: false
        default: true
        type: boolean
      env_name:
        required: true
        type: string
      app_name:
        required: false
        type: string
    secrets:
      FSD_GH_APP_ID:
        required: true
      FSD_GH_APP_KEY:
        required: true
      FS_BASIC_AUTH_USERNAME:
        required: true
      FS_BASIC_AUTH_PASSWORD:
        required: true
      AWS_ACCOUNT:
        required: true

jobs:
  run_e2e_test:
    name: E2E tests (Apply and Assess)
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    environment: ${{ inputs.env_name }}
    if: ${{ inputs.run_e2e_tests == true}}
    defaults:
      run:
        working-directory: ./funding-service-design-e2e-checks
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.FSD_GH_APP_ID }}
          private-key: ${{ secrets.FSD_GH_APP_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "funding-service-design-e2e-checks"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GithubCopilotDeploy
          role-session-name: "${{ inputs.app_name }}_${{ inputs.environment }}_copilot_${{ steps.currentdatetime.outputs.datetime }}"
          aws-region: eu-west-2

      - name: Checkout E2E tests
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: communitiesuk/funding-service-design-e2e-checks
          path: ./funding-service-design-e2e-checks
          token: ${{ steps.generate_token.outputs.token }}

      - name: 'Set unique id'
        id: unique_id
        run: |
          echo "unique_id=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5
        with:
          enable-cache: true
      - name: Install playwright browsers
        # working-directory: funding-service-design-e2e-checks
        run: uv run --frozen playwright install --with-deps chromium

      - name: Run Python E2E tests
        working-directory: ./funding-service-design-e2e-checks/tests
        run: uv run --frozen pytest --e2e-env "$ENV_NAME" --tracing=retain-on-failure --browser chromium
        env:
          ENV_NAME: ${{ inputs.env_name }}
          FS_BASIC_AUTH_USERNAME: ${{ secrets.FS_BASIC_AUTH_USERNAME }}
          FS_BASIC_AUTH_PASSWORD: ${{ secrets.FS_BASIC_AUTH_PASSWORD }}

      - name: Upload E2E Test Report
        if: success() || failure()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: e2e-test-report-assessment-${{inputs.env_name}}-${{ steps.unique_id.outputs.unique_id }}
          path: ./funding-service-design-e2e-checks/results
          retention-days: 5
  cleanup_e2e_data:
    name: Cleanup E2E Test Data
    if: ${{ always() && (inputs.env_name == 'dev' || inputs.env_name == 'test' || inputs.env_name == 'uat') }}
    needs: [ run_e2e_test ]
    uses: ./.github/workflows/cleanup-e2e-data.yml
    with:
      env_name: ${{ inputs.env_name }}
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      FS_BASIC_AUTH_USERNAME: ${{ secrets.FS_BASIC_AUTH_USERNAME }}
      FS_BASIC_AUTH_PASSWORD: ${{ secrets.FS_BASIC_AUTH_PASSWORD }}
