name: Tag to release
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      build_static_assets:
        type: boolean
        required: false
        default: true
    outputs:
      new_tag:
        description: "The version created from the new tagging process"
        value: ${{ jobs.release_tag.outputs.exported_tag }}


env:
  # This uses the default config, since
  # build is not an actual config file in envs.
  FLASK_ENV : build

jobs:
  release_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      exported_tag: ${{ steps.bump-tag.outputs.new_tag }}
    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: checkout code
        uses: actions/checkout@v4
  
      - name: Bump version and push tag
        if: ${{ github.ref_type != 'tag' }}
        id: bump-tag
        uses: anothrNick/github-tag-action@1.61.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE_SUFFIX: prerelease
          DEFAULT_BUMP: patch
      
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with: 
          tag: ${{ steps.bump-tag.outputs.new_tag }}
          artifacts: '${{ github.event.repository.name }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Write Tag
        run: echo "### New Tag ${{ steps.bump-tag.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY
