on:
  workflow_dispatch:
  push:
    branches:
      - fs-1972-add-uat-tests
    
jobs:
  run-shared-tests:
    uses: ./.github/workflows/run-shared-tests.yml
    with:
      perf_test_target_url_application_store: https://funding-service-design-application-store-test.london.cloudapps.digital/
      perf_test_target_url_fund_store: https://funding-service-design-fund-store-test.london.cloudapps.digital/
      e2e_tests_target_url_frontend: https://fsd:fsd@frontend.test.gids.dev
      e2e_tests_target_url_authenticator: https://fsd:fsd@authenticator.test.gids.dev
      e2e_tests_target_url_form_runner: https://fsd:fsd@forms.test.gids.dev