name: Test other workflows in this repo
on:
  push:
    paths:
      - ".github/workflows/test-tag-to-release.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      assets_required:
        required: false
        default: false
        type: boolean
      postgres_unit_testing:
        required: false
        default: false
        type: boolean
      db_name:
        required: false
        default: "postgres_db"
        type: string
      run_performance_tests:
        required: false
        default: false
        type: boolean
      run_e2e_tests_application:
        required: false
        default: false
        type: boolean
      run_e2e_tests_assessment:
        required: false
        default: false
        type: boolean
      run_static_security_python:
        required: false
        default: true
        type: boolean
      app_name:
        required: false
        type: string
      environment:
        required: true
        type: string
        default: dev
      run_zap_scan:
        required: false
        default: false
        type: boolean

jobs:

  post_dev_deploy_tests:
      secrets:
        FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
        FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
      uses: ./.github/workflows/post-deploy.yml
      with:
          run_performance_tests: ${{ inputs.run_performance_tests || false }}
          run_e2e_tests_assessment: ${{ inputs.run_e2e_tests_assessment || false }}
          run_e2e_tests_application: ${{ inputs.run_e2e_tests_application || false }}
          run_static_security_python: ${{ inputs.run_static_security_python  || true}}
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}