on:
  workflow_dispatch:
  push:
    branches:
      - fs-1972-add-uat-tests
    
jobs:
  run-shared-tests:
    uses: ./.github/workflows/run-shared-tests.yml
    with:
      target_url_frontend: blahblah