on:
  workflow_dispatch:
  push:
    branches:
      - fs-1972-add-uat-tests
    
jobs:
  run-shared-tests:
    uses: ./.github/workflows/run-shared-tests.yml
    with:
      perf_test_target_url_application_store: https://funding-service-design-application-store-dev.london.cloudapps.digital/
      perf_test_target_url_fund_store: https://funding-service-design-fund-store-dev.london.cloudapps.digital/
      e2e_tests_target_url_frontend: https://fsd:fsd@frontend.dev.gids.dev
      e2e_tests_target_url_authenticator: https://fsd:fsd@authenticator2.dev.gids.dev
      e2e_tests_target_url_form_runner: https://fsd:fsd@forms.dev.gids.dev
    secrets:
       E2E_PAT: ${{secrets.E2E_PAT}}
